import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  buildBoardProvisioningRegions,
  buildNvsPartition,
  buildOtadataSelectingSlot,
  crc32,
  parsePartitionTable,
  seedBootSelectionInMergedImage,
} from "../src/nvs-image.js";

const fixture = (name: string) => new Uint8Array(readFileSync(new URL(`./fixtures/${name}`, import.meta.url)));

function partitionEntry(label: string, type: number, subtype: number, offset: number, size: number): Uint8Array {
  const entry = new Uint8Array(32);
  const dv = new DataView(entry.buffer);
  entry.set([0xaa, 0x50, type, subtype]);
  dv.setUint32(4, offset, true);
  dv.setUint32(8, size, true);
  entry.set(new TextEncoder().encode(label), 12);
  return entry;
}

describe("nvs-image", () => {
  it("crc32 matches zlib semantics", () => {
    expect(crc32(new TextEncoder().encode("123456789"))).toBe(0xcbf43926);
  });

  // Reference generated by esp-idf-nvs-partition-gen from nvs_loader_ref.csv.
  it("builds NVS images byte-identical to nvs_partition_gen", () => {
    const image = buildNvsPartition(
      {
        wifi_cfg: {
          ssid: { type: "string", value: "MyNetwork-With-A-Long-Name-32ch" },
          pass: { type: "string", value: "s3cret pass!" },
        },
        loader: { last_slot: { type: "u8", value: 0 } },
      },
      0x3000
    );
    expect(Buffer.from(image).equals(Buffer.from(fixture("nvs_loader_ref.bin")))).toBe(true);
  });

  it("builds otadata selecting ota_0 like otatool", () => {
    expect(Buffer.from(buildOtadataSelectingSlot(0)).equals(Buffer.from(fixture("otadata_ota0_ref.bin")))).toBe(true);
  });

  it("parses the partition table and builds provisioning regions", () => {
    const table = new Uint8Array(0xc00).fill(0xff);
    table.set(partitionEntry("nvs_loader", 1, 0x02, 0x9000, 0x3000), 0);
    table.set(partitionEntry("otadata", 1, 0x00, 0xc000, 0x2000), 32);
    table.set(partitionEntry("nvs", 1, 0x02, 0xe000, 0x6000), 64);
    table.set(partitionEntry("factory", 0, 0x00, 0x20000, 0xe0000), 96);
    table.set(partitionEntry("ota_0", 0, 0x10, 0x100000, 0x180000), 128);
    const partitions = parsePartitionTable(table);
    expect(partitions.map((p) => p.label)).toEqual(["nvs_loader", "otadata", "nvs", "factory", "ota_0"]);

    const regions = buildBoardProvisioningRegions(partitions, { ssid: "net", password: "pw" });
    expect(regions.map((r) => [r.address, r.data.length])).toEqual([
      [0x9000, 0x3000],
      [0xc000, 0x2000],
      [0xe000, 0x6000],
    ]);
  });

  it("rejects keys longer than 15 bytes", () => {
    expect(() => buildNvsPartition({ ns: { "sixteen_chars_xx": { type: "u8", value: 1 } } }, 0x3000)).toThrow();
  });

  it("seeds otadata and last_slot into a blank merged image", () => {
    const image = new Uint8Array(0x100010).fill(0xff);
    image.set(partitionEntry("nvs_loader", 1, 0x02, 0x9000, 0x3000), 0x8000);
    image.set(partitionEntry("otadata", 1, 0x00, 0xc000, 0x2000), 0x8020);
    image.set(partitionEntry("ota_0", 0, 0x10, 0x100000, 0x180000), 0x8040);
    image[0x100000] = 0xe9;

    const seeded = seedBootSelectionInMergedImage(image);
    expect(seeded).not.toBeNull();
    expect(Buffer.from(seeded!.subarray(0xc000, 0xe000)).equals(Buffer.from(fixture("otadata_ota0_ref.bin")))).toBe(true);
    expect(Buffer.from(seeded!.subarray(0x9000, 0xc000)).equals(
      Buffer.from(buildNvsPartition({ loader: { last_slot: { type: "u8", value: 0 } } }, 0x3000))
    )).toBe(true);
    expect(image[0xc000]).toBe(0xff);

    // Already seeded, or no app in ota_0 → left alone.
    expect(seedBootSelectionInMergedImage(seeded!)).toBeNull();
    image[0x100000] = 0xff;
    expect(seedBootSelectionInMergedImage(image)).toBeNull();
  });
});
